file(REMOVE "${RESULT_FILE}.txt" "${RESULT_FILE}.xml")
execute_process(COMMAND "${TEST_EXE}" -o "${RESULT_FILE}.txt,txt" -o "${RESULT_FILE}.xml,xml"
    RESULT_VARIABLE result TIMEOUT 15)
if(EXISTS "${RESULT_FILE}.txt")
    file(READ "${RESULT_FILE}.txt" report)
    message("${report}")
endif()
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Window procedure regression failed: ${result}")
endif()
file(READ "${RESULT_FILE}.xml" report)
string(REGEX MATCHALL "<Incident type=\"pass\"" passes "${report}")
list(LENGTH passes count)
if(NOT count EQUAL EXPECTED_PASSES OR report MATCHES "<Incident type=\"(skip|xfail)\"")
    message(FATAL_ERROR "Expected ${EXPECTED_PASSES} passes without skips; got ${count}")
endif()
