# Inspect the generated CTest registrations, including every enabled subdirectory.
# CTest JSON and string(JSON) are available with the project's CMake 3.19 minimum.
if(NOT DEFINED BUILD_DIR OR "${BUILD_DIR}" STREQUAL "")
    message(FATAL_ERROR "BUILD_DIR is required")
endif()
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${BUILD_DIR}"
    -C "${BUILD_CONFIG}" --show-only=json-v1
    RESULT_VARIABLE result OUTPUT_VARIABLE manifest ERROR_VARIABLE error TIMEOUT 5)
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Could not inspect CTest timeouts (${result}): ${error}")
endif()
string(JSON count LENGTH "${manifest}" tests)
if(count EQUAL 0)
    message(FATAL_ERROR "No tests registered; timeout policy cannot be verified")
endif()
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON name GET "${manifest}" tests ${index} name)
    string(JSON property_count LENGTH "${manifest}" tests ${index} properties)
    set(timeout "")
    if(property_count GREATER 0)
        math(EXPR property_last "${property_count} - 1")
        foreach(property_index RANGE 0 ${property_last})
            string(JSON property_name GET "${manifest}" tests ${index} properties ${property_index} name)
            if(property_name STREQUAL "TIMEOUT")
                string(JSON timeout GET "${manifest}" tests ${index} properties ${property_index} value)
            endif()
        endforeach()
    endif()
    # CTest treats TIMEOUT=0 as unlimited. Require a concrete, positive bound.
    if(NOT timeout MATCHES "^[0-9]+([.][0-9]+)?$" OR timeout LESS_EQUAL 0 OR timeout GREATER 60)
        message(FATAL_ERROR "${name}: TIMEOUT must be explicit and greater than 0, at most 60 seconds; got '${timeout}'")
    endif()
    message(STATUS "${name}: ${timeout}s")
endforeach()
message(STATUS "All ${count} registered tests have bounded timeouts")
