file(REMOVE "${RESULT_FILE}.txt" "${RESULT_FILE}.xml")
execute_process(COMMAND "${TEST_EXE}" -o "${RESULT_FILE}.txt,txt" -o "${RESULT_FILE}.xml,xml"
    RESULT_VARIABLE _result TIMEOUT 100)
if(EXISTS "${RESULT_FILE}.txt")
    file(READ "${RESULT_FILE}.txt" _report)
    message("${_report}")
endif()
if(NOT "${_result}" STREQUAL "0")
    message(FATAL_ERROR "Native hit-test regression failed: ${_result}")
endif()
file(READ "${RESULT_FILE}.xml" _xml)
string(REGEX MATCHALL "<Incident type=\"pass\"" _passes "${_xml}")
list(LENGTH _passes _pass_count)
if(NOT _pass_count EQUAL EXPECTED_PASSES OR _xml MATCHES "<Incident type=\"skip\"")
    message(FATAL_ERROR "Expected ${EXPECTED_PASSES} passes without skips; got ${_pass_count}")
endif()
