file(REMOVE "${RESULT_FILE}.txt" "${RESULT_FILE}.xml")
execute_process(COMMAND "${TEST_EXE}" -o "${RESULT_FILE}.txt,txt" -o "${RESULT_FILE}.xml,xml"
    RESULT_VARIABLE result TIMEOUT 40)
if(EXISTS "${RESULT_FILE}.txt")
    file(READ "${RESULT_FILE}.txt" report)
    message("${report}")
endif()
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Cursor regression failed or timed out: ${result}")
endif()
file(READ "${RESULT_FILE}.xml" xml)
string(REGEX MATCHALL "<Incident type=\"pass\"" passes "${xml}")
list(LENGTH passes pass_count)
if(NOT pass_count EQUAL EXPECTED_PASSES OR xml MATCHES "<Incident type=\"(skip|xfail)\"")
    message(FATAL_ERROR "Expected ${EXPECTED_PASSES} passes without skips/expected failures; got ${pass_count}")
endif()
