#ifndef QWKSTYLESUPPORTGLOBAL_H
#define QWKSTYLESUPPORTGLOBAL_H

#include <QtGlobal>

#ifndef QWK_STYLESUPPORT_EXPORT
#  ifdef QWK_STYLESUPPORT_STATIC
#    define QWK_STYLESUPPORT_EXPORT
#  else
#    ifdef QWK_STYLESUPPORT_LIBRARY
#      define QWK_STYLESUPPORT_EXPORT Q_DECL_EXPORT
#    else
#      define QWK_STYLESUPPORT_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // QWKSTYLESUPPORTGLOBAL_H
